# Repository settings managed by https://github.com/apps/settings
# Last synced: 2025-01-30 22:39
repository:
  # Repository name
  name: essex
  # Repository description
  description: A Docker project template generator written in Rust
  # Enable issues and projects
  has_issues: true
  has_projects: true
  has_wiki: false
  # Default branch
  default_branch: main
  # Allow squash merging, make it default
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  squash_merge_default: true
  # Automatically delete head branches after merging PRs
  delete_branch_on_merge: true

# Labels for issues and pull requests
labels:
  - name: release
    color: "0E8A16"
    description: "Triggers version bump workflow"
  - name: major
    color: "B60205"
    description: "Major version bump (breaking changes)"
  - name: minor
    color: "1D76DB"
    description: "Minor version bump (new features)"
  - name: patch
    color: "0E8A16"
    description: "Patch version bump (bug fixes)"
  - name: automated
    color: "BFDADC"
    description: "Automated changes"
  - name: version-bump
    color: "5319E7"
    description: "Version bump changes"

# Branch protection rules
branches:
  - name: main
    protection:
      # Require status checks
      required_status_checks:
        strict: true
        contexts: ["cargo test", "cargo fmt", "cargo clippy"]
      # Include administrators
      enforce_admins: true
      # Restrict who can push to this branch
      restrictions: null
