#!/usr/bin/env bash
# shellcheck disable=SC2034

# Setup the Essex Path
ESSEX_PATH="$(cd "$(dirname "$0")" ; pwd -P )" || exit 1

# Set Colors
bold=$(tput bold)
reset=$(tput sgr0)
purple=$(tput setaf 171)
red=$(tput setaf 1)
green=$(tput setaf 76)
tan=$(tput setaf 3)
blue=$(tput setaf 38)
underline=$(tput sgr 0 1)

# Print usage information
usage() {
	cat <<-EOF
		 ${bold}Essex $(version): Boilerplate for Docker Based Projects.${reset}
		 License: MIT Copyright (c) 2019 Utensils Union
		
		 Usage:
		 	essex list
		 	essex new <template> <ProjectName>
		 	essex update
		
		 Examples:
		  	essex new basic MyApp
		
	EOF
}

# Print version information
version() {
	git describe --tags --abbrev=0 2>/dev/null || git rev-parse --abbrev-ref HEAD
}

# List available templates
list(){
	echo "Available templates:"
	for template in "$ESSEX_PATH"/templates/*
	do
		if [ -f "$template"/.description ]
		then
			echo "  ${bold}$(basename "$template")${reset} - $(cat "$template"/.description)"
		else
			echo "  ${bold}$(basename "$template")${reset}"
		fi
	done
}

# Update Essex
update(){
	echo "Updating Essex"
	git --git-dir="$ESSEX_PATH"/.git pull origin
}

# Collect maintainer name from git
maintainer(){
	user_name="$(git config user.name)"
	email="$(git config user.email)"
	echo "$user_name <$email>"
}

# Update the project's maintainer
project_maintainer(){
	local maintainer="$1"
	sed -i 's/org.opencontainers.image.authors=.* \\/org.opencontainers.image.authors="'"$maintainer"'" \\/g' Dockerfile
}

# Update the project's name
project_name(){
	local name="$1"
	sed -r -i 's/(^IMAGE_NAME.+\?= ).+$/\1'"$name"'/g' Makefile
}

# Create a new project from a template
new(){
	local template="$2"
	local project="$3"

	echo "Creating new project $project using template: $template"
	mkdir -p "$project"
	cd "$project" || exit 1
	# If this is not already a git project lets init one now
	if [ ! -d ".git" ]
	then
		git init
	fi

	# Copy the template files into the project
	cp -r "$ESSEX_PATH"/templates/"$template"/. ./

	project_maintainer "$(maintainer)"
	project_name "${project,,}"

	git add .
	# git status
}

# Parse any subcommands
while true; do
  case "$1" in
    list) list; exit $? ;;
	new) new "$@"; exit $? ;;
	update) update; exit $? ;;
    * ) usage; exit 0 ;;
  esac
done

# Parse short and long options
OPTS=$(getopt -o vh: --long verbose,help: -n 'parse-options' -- "$@")

# shellcheck disable=SC2181
if [ $? != 0 ]
then 
	echo "Failed parsing options." >&2
	exit 1
fi

eval set -- "$OPTS"

VERBOSE=false

while true; do
  case "$1" in
    -v | --verbose ) VERBOSE=true; shift ;;
    -h | --help ) usage;break;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

exit 0
