max_width = 100
edition = "2021"
merge_derives = true
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
