name: Build Release Binaries

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS builds
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_name: essex
          - os: macos-latest
            target: aarch64-apple-darwin
            binary_name: essex
          # Linux builds
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: essex
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            binary_name: essex

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install cross-compilation tools
      if: matrix.os == 'ubuntu-latest' && contains(matrix.target, 'aarch64')
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

    - name: Build
      run: |
        cargo build --release --target ${{ matrix.target }}

    - name: Prepare artifact
      shell: bash
      run: |
        mkdir -p artifacts
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cp target/${{ matrix.target }}/release/${{ matrix.binary_name }}.exe artifacts/
        else
          cp target/${{ matrix.target }}/release/${{ matrix.binary_name }} artifacts/
        fi
        cd artifacts
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          7z a ../essex-${{ matrix.target }}.zip ${{ matrix.binary_name }}.exe
        else
          tar czf ../essex-${{ matrix.target }}.tar.gz ${{ matrix.binary_name }}
        fi
        cd ..

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: essex-${{ matrix.target }}
        path: essex-${{ matrix.target }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}
        retention-days: 5

  # Create GitHub release when a tag is pushed
  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: essex-*/*
          draft: false
          prerelease: false
          generate_release_notes: true
